### ISSUE TITLE
views of InlineStrings

### ISSUE THREAD

**Issue by bkamins** [JuliaStrings/InlineStrings.jl#17]
Currently e.g. we have:
```
julia> using InlineStrings

julia> x = InlineString("abcd")
"abcd"

julia> y = last(x, 3)
"bcd"

julia> typeof(x)
String7

julia> typeof(y)
SubString{String7}

julia> Base.summarysize(x)
8

julia> Base.summarysize(y)
24
```
which seems wasteful. Maybe for small inline strings we should have special implementation of standard functions like `first`, `last`, `chop` that would not make a view, but just create a new string of the same type as the source?

**Comment by quinnj** [comment]
For `first`/`last` we could even go to smaller inline string types? Or would we rather try to keep the same type as input?

**Comment by bkamins** [comment]
For `chop` it is the same - it cannot grow the string.

> Or would we rather try to keep the same type as input?

This is a hard question. I thought more in favor of keeping the same type as:
1. this is then type stable (shrinking the type cannot be typestable as we strip characters that might have variable byte width)
2. most likely your strings are put in some container, so it is better to keep the eltype of this container unchanged.
