### ISSUE TITLE
Aqua found ambiguity

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaStrings/InlineStrings.jl#31]
```
Ambiguity #1
defalg(::AbstractArray{<:Union{Missing, InlineStrings.String1, InlineStrings.String15, InlineStrings.String3, InlineStrings.String7}}) in InlineStrings at C:\Users\MrJSa\.julia\packages\InlineStrings\F5Dhz\src\InlineStrings.jl:698
defalg(v::AbstractArray{<:Union{Missing, Number}}) in Base.Sort at sort.jl:659

Possible fix, define
  defalg(::AbstractArray{<:Missing})
```

**Comment by bkamins** [comment]
See https://github.com/JuliaStrings/InlineStrings.jl/issues/21 and https://github.com/JuliaLang/julia/pull/43426

What version of Julia are you on? (if on an old one just add methods defined in https://github.com/JuliaLang/julia/pull/43426 manually)

**Comment by JeffreySarnoff** [comment]
I ran it on Julia 1.8-current and 1.9-current

**Comment by bkamins** [comment]
This is strange. What is the exact type of array that you are trying to sort?

**Comment by JeffreySarnoff** [comment]
Closing .. cannot reproduce the issue.

**Comment by JeffreySarnoff** [comment]
I was not trying to sort anything.
I had added InlineStrings to Project.toml and added "using InlineStrings"
in a source file.
I did not use any InlineStrings functions -- I could not because of this
error.

Just now, I tried to recreate the problem.  The issue has vanished.
Perhaps there was something amiss in the computer's state earlier.

I am closing the issue.  Thanks for the attention.
