### ISSUE TITLE
`parse(Bool, s::String3)` giving InexactError

### ISSUE THREAD

**Issue by anandijain** [JuliaStrings/InlineStrings.jl#57]
```julia 
julia> using InlineStrings

julia> String3("0")
"0"

julia> parse(Bool, String3("0"))
ERROR: InexactError: Bool(10)

julia> parse(Bool, String(String3("0")))
false
```

is this expected to work? It was confusing hitting this when working with a DataFrame

**Comment by bkamins** [comment]
This is a bug in Julia Base in my opinion.

**Comment by bkamins** [comment]
Also to be covered:
```
julia> parse(Bool, "false")
false

julia> parse(Bool, String7("false"))
ERROR: InexactError: Bool(10)
```

@quinnj - how do you want to handle this. I think:
1. A PR to Base Julia should be made copying the implementation of
```
tryparse_internal(::Type{Bool}, sbuff::Union{String,SubString{String}}, startpos::Int, endpos::Int, base::Integer, raise::Bool)
```
to
```
tryparse_internal(::Type{Bool}, sbuff::AbstractString, startpos::Int, endpos::Int, base::Integer, raise::Bool)
```
2. adding a workaround in InlineStrings.jl to make sure `parse` works for older Julia versions.

**Comment by quinnj** [comment]
Ok, PR to fix Base is up: https://github.com/JuliaLang/julia/pull/47782. Will look into what we should do in InlineStrings as well.
